Repository Workiva/eva, pull requests merged in 2019-07, with the labels that each got.

#12 fix typo in readme
  README.md
Labels: Merge Requirements Unmet

#11 Address typo in FAQ
  README.md
Labels: Merge Requirements Unmet, RM Ready

#56 Update docker images.
  docker/docker-compose.override.yml
  docker/docker-compose.repl.yml
  docker/docker-compose.yml
  project.clj
  scripts/ci/pull_composes.sh
Labels: Merge Requirements Met, RM Ready

#100 RM-53433 Release eva v2.0.3
  project.clj
Labels: Merge Requirements Met, RM Ready

#108 Remove transactor groups env var to fix issue with other catalog configs.
  docker/docker-compose.yml
Labels: Merge Requirements Met, RM Ready

#110 RM-54963 Release eva v2.0.4
  project.clj
Labels: Merge Requirements Met, RM Ready
