Repository Workiva/eva, pull requests merged in 2019-06, with the labels that each got.

#2 Add CircleCI configuration
  .circleci/clojars/profiles.clj
  .circleci/config.yml
  .circleci/scripts/update-tocs.sh
  .circleci/scripts/verify-dockerfile.sh
  .circleci/scripts/verify-docs.sh
  .circleci/scripts/verify-license-headers.sh
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Makefile
  README.md
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docs/api/eva_config_properties.md
  package.json
  project.clj
  skynet.yaml
  transactor.Dockerfile
  workivabuild.Dockerfile
Labels: Merge Requirements Met

#5 RM-52624 Release eva v2.0.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#6 Update description and licensing information in project.clj
  project.clj
Labels: Merge Requirements Unmet

#7 Re-generate docs after project.clj update
  docs/api/clojure/index.html
Labels: Merge Requirements Met, RM Ready

#9 Update CI config to use new Dockerhub account
  .circleci/config.yml
  Makefile
Labels: Merge Requirements Met, RM Ready

#10 RM-52630 Release eva v2.0.2
  project.clj
Labels: Merge Requirements Met, RM Ready
